name: ğŸš Renovate
on:
  schedule:
    - cron: "0/15 * * * *" # every 15 minutes
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸª™ Get token
        id: get_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          private-key: ${{ secrets.renovate_private_key }}
          app-id: ${{ vars.renovate_app_id }}

      - name: âœ… Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: ğŸš Self-hosted Renovate
        uses: renovatebot/github-action@f8af9272cd94a4637c29f60dea8731afd3134473 # v43.0.12
        with:
          configurationFile: .github/gha-renovate.json
          token: "${{ steps.get_token.outputs.token }}"
